/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.t;

import domen.Preparat;
import gui.modeltabele.PModelTabele;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import logic.Kontroler;

/**
 *
 * @author Megi
 */
public class FDetalji extends javax.swing.JFrame {

    private List<Preparat> listaDesno;
    private List<Preparat> listaLevo;
    private PModelTabele pmt;
    private DefaultListModel<Preparat> dlm;
    private ArrayList<Preparat> lp;
    private int tretmanID;

    /**
     * Creates new form FDetalji
     */
    public FDetalji() throws ClassNotFoundException, SQLException, IOException {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblPreparati = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListIzabraniPreparati = new javax.swing.JList();
        jbtnDodajPreparat = new javax.swing.JButton();
        jbtnObrisiPreparat = new javax.swing.JButton();
        jbtnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("Svi preparati:");

        jLabel3.setText("Izabrani preparati:");

        jtblPreparati.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jtblPreparati);

        jScrollPane4.setViewportView(jListIzabraniPreparati);

        jbtnDodajPreparat.setText("->");
        jbtnDodajPreparat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajPreparatActionPerformed(evt);
            }
        });

        jbtnObrisiPreparat.setText("<-");
        jbtnObrisiPreparat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiPreparatActionPerformed(evt);
            }
        });

        jbtnSacuvaj.setText("Sačuvaj");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addComponent(jLabel4)
                            .addGap(347, 347, 347))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jbtnSacuvaj)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jbtnDodajPreparat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbtnObrisiPreparat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addComponent(jbtnDodajPreparat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jbtnObrisiPreparat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))))
                    .addGap(66, 66, 66)
                    .addComponent(jbtnSacuvaj)
                    .addContainerGap(20, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDodajPreparatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajPreparatActionPerformed
        if (!listaLevo.isEmpty() && jtblPreparati.getSelectedRow()> -1) {
            listaDesno.add(listaLevo.get(jtblPreparati.getSelectedRow()));
            listaLevo.remove(jtblPreparati.getSelectedRow());
            pmt = new PModelTabele(listaLevo);
            jtblPreparati.setModel(pmt);
            dlm = new DefaultListModel<Preparat>();
            for (Preparat p : listaDesno) {
                dlm.addElement(p);
            }
            jListIzabraniPreparati.setModel(dlm);
        }
    }//GEN-LAST:event_jbtnDodajPreparatActionPerformed

    private void jbtnObrisiPreparatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiPreparatActionPerformed
        if (!listaDesno.isEmpty() && jListIzabraniPreparati.getSelectedIndex() > -1) {
            listaLevo.add(listaDesno.get(jListIzabraniPreparati.getSelectedIndex()));
            listaDesno.remove(jListIzabraniPreparati.getSelectedIndex());
            pmt = new PModelTabele(listaLevo);
            jtblPreparati.setModel(pmt);
            dlm = new DefaultListModel<Preparat>();
            for (Preparat p : listaDesno) {
                dlm.addElement(p);
            }
            jListIzabraniPreparati.setModel(dlm);
        }
    }//GEN-LAST:event_jbtnObrisiPreparatActionPerformed

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed

        boolean validacija = true;

        lp = new ArrayList<Preparat>();

        ListModel model = jListIzabraniPreparati.getModel();
        for (int i = 0; i < model.getSize(); i++) {
            Preparat p = (Preparat) model.getElementAt(i);
            lp.add(p);
        }
        try {
            Kontroler.vratiInstancu().izmeniPreparate(tretmanID, lp);
        } catch (ClassNotFoundException ex) {
            System.out.println(ex.getMessage());
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }


    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FDetalji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FDetalji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FDetalji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FDetalji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FDetalji().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(FDetalji.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(FDetalji.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(FDetalji.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jListIzabraniPreparati;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jbtnDodajPreparat;
    private javax.swing.JButton jbtnObrisiPreparat;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JTable jtblPreparati;
    // End of variables declaration//GEN-END:variables

    public int getTretmanID() {
        return tretmanID;
    }

    public void setTretmanID(int tretmanID) {
        this.tretmanID = tretmanID;
    }

    public void srediFormu() throws ClassNotFoundException, SQLException, IOException {

        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

        listaDesno = Kontroler.vratiInstancu().vratiSvePreparateTretmana(tretmanID);
        DefaultListModel dlm = new DefaultListModel();
        for (int i = 0; i < listaDesno.size(); i++) {
            dlm.addElement(listaDesno.get(i));
        }
        jListIzabraniPreparati.setModel(dlm);
        listaLevo = new ArrayList<>(Kontroler.vratiInstancu().vratiSvePreparate());

        for (int i = 0; i < listaLevo.size(); i++) {
            for (int j = 0; j < listaDesno.size(); j++) {
                if (listaLevo.get(i).equals(listaDesno.get(j))) {
                    listaLevo.remove(i);
                }
            }
        }

        PModelTabele pmt = new PModelTabele(listaLevo);
        jtblPreparati.setModel(pmt);

    }

}
