
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.t;

import domen.Preparat;
import domen.Tretman;
import gui.modeltabele.PModelTabele;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import logic.Kontroler;

/**
 *
 * @author student1
 */
public class FTretman extends javax.swing.JFrame {

    DefaultListModel<Preparat> dlm;
    ArrayList<Preparat> lp;
    List<Preparat> lpRef;
    PModelTabele pmt;
    List<Preparat> lista;
    List<Preparat> listaLevo;
    private List<Preparat> listaDesno;
    private Tretman tretmanIzmena;
   

    public FTretman() {
        initComponents();
        try {
            srediFormu();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FTretman.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FTretman.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FTretman.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbtnSacuvaj = new javax.swing.JButton();
        jtxtOpis = new javax.swing.JTextField();
        jtxtTrajanje = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        errDatum = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblPreparati = new javax.swing.JTable();
        jbtnObrisiPreparat = new javax.swing.JButton();
        jbtnDodajPreparat = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListIzabraniPreparati = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtPoruka = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unos tretmana");

        jLabel1.setText("Opis tretmana:");

        jbtnSacuvaj.setText("Sačuvaj");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        jtxtTrajanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTrajanjeActionPerformed(evt);
            }
        });

        jLabel5.setText("Trajanje u minutima:");

        errDatum.setForeground(new java.awt.Color(255, 0, 0));

        jtblPreparati.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jtblPreparati);

        jbtnObrisiPreparat.setText("<-");
        jbtnObrisiPreparat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiPreparatActionPerformed(evt);
            }
        });

        jbtnDodajPreparat.setText("->");
        jbtnDodajPreparat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajPreparatActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(jListIzabraniPreparati);

        jLabel3.setText("Izabrani preparati:");

        jLabel4.setText("Svi preparati:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(jtxtOpis, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jtxtTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtnSacuvaj)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbtnDodajPreparat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtnObrisiPreparat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jtxtPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jtxtOpis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addComponent(jtxtTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jbtnDodajPreparat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnObrisiPreparat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jtxtPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jbtnSacuvaj)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed

        String opis = jtxtOpis.getText().trim();
        String trajanje = jtxtTrajanje.getText().trim();
        double cena = 0;
        boolean validacija = true;

        if (opis == null || opis.equals("") || trajanje == null || trajanje.equals("")) {
            validacija = false;
        }

        if (validacija == true) {
            Tretman t = new Tretman();
            t.setOpis(opis);
            t.setTrajanjeUMin(Integer.parseInt(trajanje));

            lp = new ArrayList<Preparat>();

            ListModel model = jListIzabraniPreparati.getModel();
            for (int i = 0; i < model.getSize(); i++) {
                Preparat p = (Preparat) model.getElementAt(i);
                lp.add(p);
                cena += p.getCena();
            }
            t.setCena(cena);
            t.setListaPreparata(lp);
            try {
                Kontroler.vratiInstancu().unesiTretman(t);
            } catch (SQLException ex) {
                Logger.getLogger(FTretman.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FTretman.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(FTretman.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                resetujFormu();
                jtxtPoruka.setVisible(true);
                jtxtPoruka.setText("Uspesno ste uneli tretman!");

            } catch (Exception e) {
                jtxtPoruka.setText(e.getMessage());
            }
        } else {
            jtxtPoruka.setText("Morate popuniti sva polja!");

        }


    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    private void jtxtTrajanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTrajanjeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTrajanjeActionPerformed

    private void jbtnObrisiPreparatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiPreparatActionPerformed
        listaLevo.add(listaDesno.get(jListIzabraniPreparati.getSelectedIndex()));
        listaDesno.remove(jListIzabraniPreparati.getSelectedIndex());
        pmt = new PModelTabele(listaLevo);
        jtblPreparati.setModel(pmt);
        dlm = new DefaultListModel<Preparat>();
        for (Preparat p : listaDesno) {
            dlm.addElement(p);
        }
        jListIzabraniPreparati.setModel(dlm);
    }//GEN-LAST:event_jbtnObrisiPreparatActionPerformed

    private void jbtnDodajPreparatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajPreparatActionPerformed
        listaDesno.add(listaLevo.get(jtblPreparati.getSelectedRow()));
        listaLevo.remove(jtblPreparati.getSelectedRow());
        pmt = new PModelTabele(listaLevo);
        jtblPreparati.setModel(pmt);
        dlm = new DefaultListModel<Preparat>();
        for (Preparat p : listaDesno) {
            dlm.addElement(p);
        }
        jListIzabraniPreparati.setModel(dlm);
    }//GEN-LAST:event_jbtnDodajPreparatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FTretman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FTretman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FTretman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FTretman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FTretman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errDatum;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jListIzabraniPreparati;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton jbtnDodajPreparat;
    private javax.swing.JButton jbtnObrisiPreparat;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JTable jtblPreparati;
    private javax.swing.JTextField jtxtOpis;
    private javax.swing.JTextField jtxtPoruka;
    private javax.swing.JTextField jtxtTrajanje;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() throws ClassNotFoundException, SQLException, IOException {
        jtxtPoruka.setEditable(false);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

        lista = new ArrayList<Preparat>();
        listaLevo = Kontroler.vratiInstancu().vratiSvePreparate();

        pmt = new PModelTabele(listaLevo);
        jtblPreparati.setModel(pmt);

        listaDesno = new ArrayList<Preparat>();
        dlm = new DefaultListModel();
        jListIzabraniPreparati.setModel(dlm);

       

    }
   
    private void resetujFormu() throws ClassNotFoundException, SQLException, IOException {
        jtxtOpis.setText("");
        jtxtTrajanje.setText("");
        jtxtPoruka.setText("");
        errDatum.setText("");
        listaLevo = new ArrayList<Preparat>(Kontroler.vratiInstancu().vratiSvePreparate());

        pmt = new PModelTabele(listaLevo);
        jtblPreparati.setModel(pmt);

        listaDesno = new ArrayList<Preparat>();
        dlm = new DefaultListModel();
        jListIzabraniPreparati.setModel(dlm);

    }
}
