/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.t;

import domen.Tretman;
import gui.modeltabele.ButtonEditor;
import gui.modeltabele.ButtonRenderer;
import gui.modeltabele.TModelTabele;
import gui.modeltabele.TableCellListener;
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JCheckBox;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.text.BadLocationException;
import logic.Kontroler;


/**
 *
 * @author student1
 */
public class FTretmanPrikaz extends javax.swing.JFrame {

    private List<Tretman> ltRef;
    private List<Tretman> lt;
    private TModelTabele tmt;

    /**
     * Creates new form FPoslovniPartnerPrikaz
     */
    public FTretmanPrikaz() throws ClassNotFoundException, SQLException, IOException {
        super();
        initComponents();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtPretraga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblTretmani = new javax.swing.JTable();
        jbtnObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Prikaz tretmana");

        jLabel1.setText("Tretman:");

        jtblTretmani.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblTretmani);

        jbtnObrisi.setText("Obriši");
        jbtnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jbtnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtPretraga))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnObrisi)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiActionPerformed
        int red = jtblTretmani.getSelectedRow();
        int tretmanID = (int) jtblTretmani.getModel().getValueAt(red, 0);
        try {
            Kontroler.vratiInstancu().obrisiTretman(tretmanID);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FTretmanPrikaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FTretmanPrikaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FTretmanPrikaz.class.getName()).log(Level.SEVERE, null, ex);
        }

        List<Tretman> lt = null;
        try {
            lt = Kontroler.vratiInstancu().vratiSveTretmane();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FTretmanPrikaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FTretmanPrikaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FTretmanPrikaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        TModelTabele pmt = new TModelTabele(lt);
        jtblTretmani.setModel(pmt);
    }//GEN-LAST:event_jbtnObrisiActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnObrisi;
    private javax.swing.JTable jtblTretmani;
    private javax.swing.JTextField jtxtPretraga;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() throws ClassNotFoundException, SQLException, IOException {

        ltRef = Kontroler.vratiInstancu().vratiSveTretmane();

        lt = new ArrayList<Tretman>(ltRef);
        tmt = new TModelTabele(lt);
        jtblTretmani.setModel(tmt);

        Action action = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                TableCellListener tcl = (TableCellListener) e.getSource();
                System.out.println("Row   : " + tcl.getRow());
                System.out.println("Column: " + tcl.getColumn());
                System.out.println("Old   : " + tcl.getOldValue());
                System.out.println("New   : " + tcl.getNewValue());

            }
        };

        jtblTretmani.addPropertyChangeListener(new TableCellListener(jtblTretmani, action));

//        new TableModelListener() {
//
//            @Override
//            public void tableChanged(TableModelEvent e) {
//                int red = e.getFirstRow();
//                int tretmanID = (int) jtblTretmani.getModel().getValueAt(red, 0);
//                String opis = (String) jtblTretmani.getModel().getValueAt(red, 1);
//                double cena = (double) jtblTretmani.getModel().getValueAt(red, 1);
//                int trajanje = (int) jtblTretmani.getModel().getValueAt(red, 0);
//
//                try {
//                    Kontroler.vratiInstancu().izmeniTretman(tretmanID, opis, cena, trajanje);
//                } catch (ClassNotFoundException ex) {
//                    Logger.getLogger(FTretmanPrikaz.class.getName()).log(Level.SEVERE, null, ex);
//                } catch (SQLException ex) {
//                    Logger.getLogger(FTretmanPrikaz.class.getName()).log(Level.SEVERE, null, ex);
//                } catch (IOException ex) {
//                    Logger.getLogger(FTretmanPrikaz.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
        TableColumnModel tcm = jtblTretmani.getColumnModel();
        TableColumn tc = tcm.getColumn(4);

        jtblTretmani.getColumn("Preparati").setCellRenderer(new ButtonRenderer());

        jtblTretmani.getColumn("Preparati").setCellEditor(
                new ButtonEditor(new JCheckBox(), jtblTretmani));

        jtxtPretraga.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {

            }

            public void removeUpdate(DocumentEvent e) {
                filter();
            }

            public void insertUpdate(DocumentEvent e) {
                filter();
            }

            public void filter() {
                String slova = "";
                try {
                    slova = jtxtPretraga.getDocument().getText(0, jtxtPretraga.getDocument().getLength());
                } catch (BadLocationException ex) {
                    Logger.getLogger(FTretmanPrikaz.class.getName()).log(Level.SEVERE, null, ex);
                }
                lt = new ArrayList<Tretman>(ltRef);
                for (int i = 0; i < lt.size(); i++) {
                    if (!lt.get(i).getOpis().contains(slova)) {
                        lt.remove(i);
                    }
                }
                if (lt.size() == 1) {
                    if (!lt.get(0).getOpis().contains(slova)) {
                        lt.remove(0);
                    }
                }

                tmt = new TModelTabele(lt);
                jtblTretmani.setModel(tmt);

            }
        });

    }
}
